//
// FlightSimAdventureCreator 1.0 (GUI Version)
//
// (c) Paul Alan Freshney 2022
//
// paul@freshney.org
//
// https://github.com/MaximumOctopus/FlightSimAdventureCreator
//
//

#ifndef mainH
#define mainH
//---------------------------------------------------------------------------
#include <System.Classes.hpp>
#include <Vcl.Controls.hpp>
#include <Vcl.StdCtrls.hpp>
#include <Vcl.Forms.hpp>
#include <Vcl.ComCtrls.hpp>
#include <Vcl.Menus.hpp>
#include <Vcl.ToolWin.hpp>
#include <System.ImageList.hpp>
#include <Vcl.ExtCtrls.hpp>
#include <Vcl.ImgList.hpp>

#include "AircraftHandler.h"
#include "AirportHandler.h"
#include "FlightHandler.h"
#include <Vcl.Dialogs.hpp>
#include <Vcl.Grids.hpp>
#include <Vcl.Graphics.hpp>


class TfrmMain : public TForm
{
__published:	// IDE-managed Components
	TToolBar *ToolBar1;
	TToolButton *tbSave;
	TToolButton *tbOpen;
	TMainMenu *MainMenu1;
	TMenuItem *File1;
	TMenuItem *File2;
	TMenuItem *Exit1;
	TMenuItem *Exit2;
	TStatusBar *sbMain;
	TImageList *ImageList1;
	TToolButton *ToolButton3;
	TSaveDialog *sdMain;
	TOpenDialog *odMain;
	TToolButton *tbExport;
	TToolButton *tbExportItinerary;
	TMenuItem *ools1;
	TMenuItem *Createcustomaircrafttxt1;
	TMenuItem *Help1;
	TMenuItem *About1;
	TMemo *mMain;
	TToolButton *ToolButton2;
	TGroupBox *gbGo;
	TButton *bGenerate;
	TCheckBox *cbKeepTrying;
	TGroupBox *GroupBox4;
	TLabel *Label21;
	TLabel *Label22;
	TLabel *lStatsAircraft;
	TLabel *lStatsAirport;
	TLabel *Label23;
	TMenuItem *Ai1;
	TMenuItem *Set1;
	TMenuItem *miSetGA;
	TMenuItem *GA2;
	TMenuItem *wins1;
	TMenuItem *Props1;
	TMenuItem *urbos1;
	TMenuItem *Seaplanes1;
	TMenuItem *Searcg1;
	TMenuItem *Airports1;
	TGroupBox *gbAirports;
	TBevel *Bevel5;
	TBevel *Bevel6;
	TLabel *Label24;
	TButton *bUpdateAirports;
	TCheckBox *cbLargeAirports;
	TCheckBox *cbMediumAirports;
	TCheckBox *cbSmallAirports;
	TCheckBox *cbHeliports;
	TCheckBox *cbSeaplaneBases;
	TCheckBox *cbTimeOfDay;
	TRadioButton *rbDay;
	TRadioButton *rbNight;
	TImageList *il16x16;
	TLabel *lStatsRunways;
	TLabel *Label30;
	TMenuItem *N1;
	TMenuItem *Favourites1;
	TBevel *Bevel13;
	TLabel *Label18;
	TEdit *eMinElevation;
	TLabel *Label20;
	TGroupBox *gbAircraft;
	TBevel *Bevel12;
	TLabel *lMinSpeed;
	TLabel *Label1;
	TLabel *Label2;
	TLabel *Label3;
	TBevel *Bevel8;
	TLabel *lAircraftStats;
	TLabel *Label26;
	TLabel *Label25;
	TEdit *eMinSpeed;
	TCheckBox *cbAircraftTypeProps;
	TCheckBox *cbAircraftTypeTwinProps;
	TCheckBox *cbAircraftTypeTurboProps;
	TCheckBox *cbAircraftTypeHelicopter;
	TCheckBox *cbAircraftTypeGlider;
	TCheckBox *cbAircraftTypeAirliners;
	TCheckBox *cbAircraftTypeMilitary;
	TCheckBox *cbAircraftTypeTwinTurboProps;
	TCheckBox *cbAircraftTypeJet;
	TCheckBox *cbAircraftTypeBalloon;
	TComboBox *cbAircraftList;
	TButton *bUpdateAircraft;
	TCheckBox *cbAircraftTypeSeaplanes;
	TEdit *eMaxSpeed;
	TComboBox *cbMSFSVersion;
	TEdit *eAircraftRangeModifier;
	TButton *bRandomAircraft;
	TButton *bLockAircraft;
	TMenuItem *N2;
	TMenuItem *Militaryjets1;
	TMenuItem *Militarypropsturbo1;
	TMenuItem *N3;
	TMenuItem *miShowTooltips;
	TToolButton *tbCodeTest;
	TEdit *eMagicCode;
	TPopupMenu *puSelectICAO;
	TMenuItem *PopupMenu11;
	TMenuItem *N4;
	TMenuItem *Select1;
	TMenuItem *N5;
	TMenuItem *miUseHomeAirport;
	TMenuItem *SetasHomeairport1;
	TPopupMenu *puRegionSelect;
	TMenuItem *UnitedKingdom1;
	TMenuItem *England1;
	TMenuItem *England2;
	TMenuItem *NorthernIreland1;
	TMenuItem *NorthernIreland2;
	TMenuItem *Australia1;
	TMenuItem *NewSouthWales1;
	TMenuItem *NewSouthWales2;
	TMenuItem *SouthAustralia1;
	TMenuItem *SouthAustralia2;
	TMenuItem *Vistoria1;
	TMenuItem *Vistoria2;
	TMenuItem *UnitedStatesofAmerica1;
	TMenuItem *Alabama1;
	TMenuItem *Alabama2;
	TMenuItem *Arizona1;
	TMenuItem *Arizona2;
	TMenuItem *California1;
	TMenuItem *California2;
	TMenuItem *Connecticut1;
	TMenuItem *Connecticut2;
	TMenuItem *Florida1;
	TMenuItem *Florida2;
	TMenuItem *Hawaii1;
	TMenuItem *Hawaii2;
	TMenuItem *Illinois1;
	TMenuItem *Illinois2;
	TMenuItem *Iowa1;
	TMenuItem *Iowa2;
	TMenuItem *Kentucky1;
	TMenuItem *Kentucky2;
	TMenuItem *Maine1;
	TMenuItem *Maine2;
	TMenuItem *Massachusetts1;
	TMenuItem *Massachusetts2;
	TMenuItem *Minnesota1;
	TMenuItem *Minnesota2;
	TMenuItem *Missouri1;
	TMenuItem *Missouri2;
	TMenuItem *Nebraska1;
	TMenuItem *Nebraska2;
	TMenuItem *NewJersey1;
	TMenuItem *NewJersey2;
	TMenuItem *NewYork1;
	TMenuItem *NewYork2;
	TMenuItem *NorthDakota1;
	TMenuItem *NorthDakota2;
	TMenuItem *Oklahoma1;
	TMenuItem *Oklahoma2;
	TMenuItem *Pennsylvania1;
	TMenuItem *Pennsylvania2;
	TMenuItem *SouthCarolina1;
	TMenuItem *SouthCarolina2;
	TMenuItem *ennessee1;
	TMenuItem *ennessee2;
	TMenuItem *Utah1;
	TMenuItem *Utah2;
	TMenuItem *Virginia1;
	TMenuItem *Virginia2;
	TMenuItem *WestVirginia1;
	TMenuItem *WestVirginia2;
	TMenuItem *Wyoming1;
	TMenuItem *Wyoming2;
	TMenuItem *DisctrictofColumbia1;
	TMenuItem *Nevada1;
	TMenuItem *Canada1;
	TMenuItem *Alberta1;
	TMenuItem *Alberta2;
	TMenuItem *Manitoba1;
	TMenuItem *Manitoba2;
	TMenuItem *NewfoundlandandLabrador1;
	TMenuItem *NewfoundlandandLabrador2;
	TMenuItem *Ontario1;
	TMenuItem *Ontario2;
	TMenuItem *PrinceEdwardIsland1;
	TMenuItem *Quebec1;
	TMenuItem *Quebec2;
	TMenuItem *NorthwestTerritories1;
	TMenuItem *NorthwestTerritories2;
	TMenuItem *N6;
	TMenuItem *NewZealand1;
	TMenuItem *Auckland1;
	TMenuItem *Auckland2;
	TMenuItem *Canterbury1;
	TMenuItem *Canterbury2;
	TMenuItem *HawkesBay1;
	TMenuItem *HawkesBay2;
	TMenuItem *ManawatuWanganui1;
	TMenuItem *ManawatuWanganui2;
	TMenuItem *Northland1;
	TMenuItem *Northland2;
	TMenuItem *Southland1;
	TMenuItem *Southland2;
	TMenuItem *aranaki1;
	TMenuItem *aranaki2;
	TMenuItem *Wellington1;
	TMenuItem *Wellington2;
	TMenuItem *France1;
	TMenuItem *Ain1;
	TMenuItem *Ain2;
	TMenuItem *Bretagne1;
	TMenuItem *CentreValdeLoire1;
	TMenuItem *Corse1;
	TMenuItem *Corse2;
	TMenuItem *HautsdeFrance1;
	TMenuItem *HautsdeFrance2;
	TMenuItem *Normandie1;
	TMenuItem *Normandie2;
	TMenuItem *Occitanie1;
	TMenuItem *Occitanie2;
	TMenuItem *ProvenceAlpesCtedAzur1;
	TMenuItem *Spain1;
	TMenuItem *Andaluca1;
	TMenuItem *Andaluca2;
	TMenuItem *AsturiasPrincipadode1;
	TMenuItem *AsturiasPrincipadode2;
	TMenuItem *Cantabria1;
	TMenuItem *Cantabria2;
	TMenuItem *CastillaLaMancha1;
	TMenuItem *CatalunyacaCatalua1;
	TMenuItem *CatalunyacaCatalua2;
	TMenuItem *Extremadura1;
	TMenuItem *Extremadura2;
	TMenuItem *llesBalearscaIslasBaleares1;
	TMenuItem *llesBalearscaIslasBaleares2;
	TMenuItem *MadridComunidadde1;
	TMenuItem *MadridComunidadde2;
	TMenuItem *MurciaReginde1;
	TMenuItem *MurciaReginde2;
	TMenuItem *asVasco1;
	TMenuItem *ValencianaComunitat1;
	TMenuItem *N7;
	TMenuItem *N8;
	TPopupMenu *puDirection;
	TMenuItem *SetDirection1;
	TMenuItem *SetDirection2;
	TMenuItem *Frombearing1;
	TMenuItem *N9;
	TMenuItem *N10;
	TMenuItem *NE1;
	TMenuItem *NE2;
	TMenuItem *E1;
	TMenuItem *E2;
	TMenuItem *SE1;
	TMenuItem *SE2;
	TMenuItem *S1;
	TMenuItem *S2;
	TMenuItem *SW1;
	TMenuItem *SW2;
	TMenuItem *W1;
	TMenuItem *W2;
	TMenuItem *NW1;
	TMenuItem *NW2;
	TMenuItem *Fromangle1;
	TMenuItem *N01;
	TMenuItem *N02;
	TMenuItem *N901;
	TMenuItem *N902;
	TMenuItem *N1801;
	TMenuItem *N1802;
	TMenuItem *N2701;
	TMenuItem *N2702;
	TMenuItem *Gliders1;
	TMenuItem *Helicopters1;
	TMenuItem *AirlinersPropTurbo1;
	TMenuItem *Brazil1;
	TMenuItem *N11;
	TMenuItem *Alagoas1;
	TMenuItem *Alagoas2;
	TMenuItem *Amazonas1;
	TMenuItem *Amazonas2;
	TMenuItem *Cear1;
	TMenuItem *Cear2;
	TMenuItem *Gois1;
	TMenuItem *Maranho1;
	TMenuItem *MatoGrosso1;
	TMenuItem *MatoGrossodoSul1;
	TMenuItem *MinasGerais1;
	TMenuItem *Par1;
	TMenuItem *Paraba1;
	TMenuItem *Paran1;
	TMenuItem *Pernambuco1;
	TMenuItem *Piau1;
	TMenuItem *RiodeJaneiro1;
	TMenuItem *RioGrandedoNorte1;
	TMenuItem *RioGrandedoSul1;
	TMenuItem *Rondnia1;
	TMenuItem *Roraima1;
	TMenuItem *SantaCatarina1;
	TMenuItem *SoPaulo1;
	TMenuItem *Sergipe1;
	TMenuItem *ocantins1;
	TBevel *Bevel14;
	TMenuItem *DistancefromAtoB1;
	TMenuItem *N12;
	TMenuItem *N13;
	TMenuItem *N14;
	TMenuItem *UAE1;
	TMenuItem *UAE2;
	TMenuItem *InnsbruckAirport1;
	TMenuItem *InnsbruckAirport2;
	TMenuItem *Australia2;
	TMenuItem *CambridgeBayAirport1;
	TMenuItem *CambridgeBayAirport2;
	TMenuItem *ParaburdooAirport1;
	TMenuItem *ShellharbourAirport1;
	TMenuItem *SydneyKingsfordSmithAirport1;
	TMenuItem *SydneyKingsfordSmithAirport2;
	TMenuItem *GustafIIIAirport1;
	TMenuItem *GustafIIIAirport2;
	TMenuItem *RiodeJaneiroGaleoInternationalAirport1;
	TMenuItem *Bhutan1;
	TMenuItem *ParoInternationalAirport1;
	TMenuItem *Canada2;
	TMenuItem *BellaCoolaAirport1;
	TMenuItem *BillyBishopTorontoCityAirport1;
	TMenuItem *BillyBishopTorontoCityAirport2;
	TMenuItem *DawsonCityAirport1;
	TMenuItem *DawsonCityAirport2;
	TMenuItem *IqaluitInternationalAirport1;
	TMenuItem *StewartAerodrome1;
	TMenuItem *CostaRica1;
	TMenuItem *SirenaAerodrome1;
	TMenuItem *SirenaAerodrome2;
	TMenuItem *BornholmAirport1;
	TMenuItem *BornholmAirport2;
	TMenuItem *MariscalSucreInternationalAirport1;
	TMenuItem *MariscalSucreInternationalAirport2;
	TMenuItem *CairoInternationalAirport1;
	TMenuItem *CairoInternationalAirport2;
	TMenuItem *VaasaAirport1;
	TMenuItem *VaasaAirport2;
	TMenuItem *CharlesdeGaulleAirport1;
	TMenuItem *CharlesdeGaulleAirport2;
	TMenuItem *MegveAltiport1;
	TMenuItem *MegveAltiport2;
	TMenuItem *Germany1;
	TMenuItem *FrankfurtAirport1;
	TMenuItem *FrankfurtAirport2;
	TMenuItem *LeipzigHalleAirport1;
	TMenuItem *LeipzigHalleAirport2;
	TMenuItem *MemmingenAirport1;
	TMenuItem *MemmingenAirport2;
	TMenuItem *GreatBritain1;
	TMenuItem *BarraAirport1;
	TMenuItem *BarraAirport2;
	TMenuItem *LandsEndAirport1;
	TMenuItem *LandsEndAirport2;
	TMenuItem *ManchesterCityAirportHeliport1;
	TMenuItem *ManchesterCityAirportHeliport2;
	TMenuItem *Gibraltar1;
	TMenuItem *GibraltarInternationalAirport1;
	TMenuItem *GibraltarInternationalAirport2;
	TMenuItem *KaiTakInternationalAirport1;
	TMenuItem *Honduras1;
	TMenuItem *oncontinInternationalAirport1;
	TMenuItem *Ireland1;
	TMenuItem *DonegalAirport1;
	TMenuItem *DonegalAirport2;
	TMenuItem *safjrurAirport1;
	TMenuItem *Italy1;
	TMenuItem *BolzanoAirport1;
	TMenuItem *BolzanoAirport2;
	TMenuItem *IloiloInternationalAirport1;
	TMenuItem *IloiloInternationalAirport2;
	TMenuItem *Japan1;
	TMenuItem *HachijojimaAirport1;
	TMenuItem *HachijojimaAirport2;
	TMenuItem *KeramaAirport1;
	TMenuItem *KeramaAirport2;
	TMenuItem *NagasakiAirport1;
	TMenuItem *NagasakiAirport2;
	TMenuItem *SuwanosejimaAirport1;
	TMenuItem *Netherlads1;
	TMenuItem *AmsterdamAirportSchiphol1;
	TMenuItem *AmsterdamAirportSchiphol2;
	TMenuItem *RotterdamTheHagueAirport1;
	TMenuItem *RotterdamTheHagueAirport2;
	TMenuItem *enzingHillaryAirport1;
	TMenuItem *enzingHillaryAirport2;
	TMenuItem *QueenstownAirport1;
	TMenuItem *QueenstownAirport2;
	TMenuItem *hagualAirport1;
	TMenuItem *Indonesia1;
	TMenuItem *BugalagaAirstrip1;
	TMenuItem *BugalagaAirstrip2;
	TMenuItem *CristianoRonaldoMadeiraInternationalAirport1;
	TMenuItem *CristianoRonaldoMadeiraInternationalAirport2;
	TMenuItem *PicoAirport1;
	TMenuItem *PicoAirport2;
	TMenuItem *PrincessJulianaInternationalAirport1;
	TMenuItem *PrincessJulianaInternationalAirport2;
	TMenuItem *CapeTownInternationalAirport1;
	TMenuItem *CapeTownInternationalAirport2;
	TMenuItem *ACoruaAirport1;
	TMenuItem *ACoruaAirport2;
	TMenuItem *AndorraLaSeudUrgellAirport1;
	TMenuItem *AndorraLaSeudUrgellAirport2;
	TMenuItem *SvalbardAirport1;
	TMenuItem *SvalbardAirport2;
	TMenuItem *StockholmArlandaAirport1;
	TMenuItem *StockholmArlandaAirport2;
	TMenuItem *LuganoAirport1;
	TMenuItem *LuganoAirport2;
	TMenuItem *StGallenAltenrheinAirport1;
	TMenuItem *ZurichAirport1;
	TMenuItem *Uganda1;
	TMenuItem *EntebbeInternationalAirport1;
	TMenuItem *DubaiInternationalAirport1;
	TMenuItem *USA1;
	TMenuItem *AspenPitkinCountyAirport1;
	TMenuItem *AspenPitkinCountyAirport2;
	TMenuItem *CatalinaAirport1;
	TMenuItem *CatalinaAirport2;
	TMenuItem *DenverInternationalAirport1;
	TMenuItem *FirstFlightAirportKittyHawk1;
	TMenuItem *FirstFlightAirportKittyHawk2;
	TMenuItem *HartsfieldJacksonAtlantaInternationalAirport1;
	TMenuItem *HartsfieldJacksonAtlantaInternationalAirport2;
	TMenuItem *LakeTahoeAirport1;
	TMenuItem *LakeTahoeAirport2;
	TMenuItem *MarineCorpsAirStationMiramar1;
	TMenuItem *MarineCorpsAirStationMiramar2;
	TMenuItem *OHareInternationalAirport1;
	TMenuItem *OHareInternationalAirport2;
	TMenuItem *PatrickSpaceForceBase1;
	TMenuItem *PatrickSpaceForceBase2;
	TMenuItem *SeattleTacomaInternationalAirport1;
	TMenuItem *SeattleTacomaInternationalAirport2;
	TMenuItem *StewartInternationalAirport1;
	TMenuItem *StewartInternationalAirport2;
	TMenuItem *ValdezAirport1;
	TMenuItem *NorthAmerica1;
	TMenuItem *SouthAmerica1;
	TMenuItem *Europe1;
	TMenuItem *Africa1;
	TMenuItem *Australasia1;
	TMenuItem *Asia1;
	TMenuItem *MiddleEast1;
	TLabel *lMinElevationRange;
	TLabel *Label36;
	TLabel *lStatsRoutes;
	TMenuItem *miNew;
	TMenuItem *N15;
	TToolButton *tbNew;
	TToolButton *ToolButton4;
	TMenuItem *N16;
	TMenuItem *N17;
	TMenuItem *N18;
	TMenuItem *Edit4;
	TMenuItem *Reset1;
	TMenuItem *miResetAircraft;
	TMenuItem *miResetAirports;
	TMenuItem *miResetRoute;
	TMenuItem *Routes1;
	TMenuItem *miRouteBrowser;
	TMenuItem *GisborneAirport1;
	TMenuItem *MilfordSoundAirport1;
	TMenuItem *MartinsBayAerodrome1;
	TMenuItem *GorgeRiverAirstrip1;
	TMenuItem *RotoruaAirport1;
	TMenuItem *LakeTekapoAirport1;
	TMenuItem *WhangareiAirport1;
	TMenuItem *WestportAirport1;
	TMenuItem *QuintinLodgeAirstrip1;
	TMenuItem *Pacific1;
	TMenuItem *EasterIsland1;
	TMenuItem *Hawaii3;
	TMenuItem *SolomanIslandsNusatupeAirport1;
	TMenuItem *BoraBoraAirport1;
	TMenuItem *IslandofMoorea1;
	TMenuItem *CookIslandsAitutakiAirport1;
	TMenuItem *PohnpeiIsland1;
	TMenuItem *AdisumarmoInternationalAirport1;
	TGroupBox *GroupBox2;
	TPageControl *pcRoute;
	TTabSheet *TabSheet1;
	TBevel *Bevel7;
	TLabel *Label9;
	TLabel *Label10;
	TLabel *Label16;
	TBevel *Bevel9;
	TLabel *Label11;
	TLabel *Label13;
	TLabel *Label29;
	TLabel *Label14;
	TLabel *Label12;
	TLabel *lDistanceStartEnd;
	TLabel *Label4;
	TLabel *Label17;
	TBevel *Bevel11;
	TBevel *Bevel10;
	TLabel *Label28;
	TLabel *Label32;
	TCheckBox *cbUseFlightTime;
	TEdit *eRange;
	TEdit *eFlightTime;
	TCheckBox *cbUseAircraftRange;
	TCheckBox *cbAllowExcessRange;
	TEdit *eStartAirportICAO;
	TCheckBox *cbStartFromFavourite;
	TCheckBox *cbEndAtFavourite;
	TRadioButton *rbStartEndRange;
	TRadioButton *rbStartEndLegs;
	TEdit *eEndAirportICAO;
	TEdit *eLegs;
	TEdit *eCount;
	TCheckBox *cbUseDirection;
	TEdit *eDirection;
	TTabSheet *TabSheet2;
	TLabel *Label8;
	TBevel *Bevel15;
	TLabel *Label15;
	TLabel *Label27;
	TBevel *Bevel17;
	TEdit *eRWRange;
	TCheckBox *cbRWUseAircraftRange;
	TCheckBox *cbRWUseFlightTime;
	TEdit *eRWFlightTime;
	TCheckBox *cbRWAllowExcessRange;
	TComboBox *cbRWAirlines;
	TLabel *Label37;
	TEdit *eRWAirport;
	TEdit *eRWRouteCount;
	TLabel *Label39;
	TBevel *Bevel18;
	TLabel *Label38;
	TBevel *Bevel16;
	TRadioButton *rbRWFromICAO;
	TRadioButton *rbRWToICAO;
	TCheckBox *cbRWAirline;
	TLabel *Label33;
	TEdit *eMaxElevation;
	TLabel *Label34;
	TLabel *lMaxElevationRange;
	TComboBox *cbRWRouteType;
	TPopupMenu *puRange;
	TMenuItem *Range1;
	TMenuItem *N19;
	TMenuItem *miRange1;
	TMenuItem *Cityhop100nm1;
	TMenuItem *Crosscountry200nm1;
	TMenuItem *International1500nm1;
	TMenuItem *Mediumhaul1;
	TMenuItem *Longhaul26001;
	TMenuItem *Domestic500nm1;
	TMenuItem *International5000nm1;
	TPopupMenu *puLongitude;
	TMenuItem *Longitude1;
	TMenuItem *N20;
	TMenuItem *AustraliaCanberra1;
	TMenuItem *AustraliaCanberra2;
	TMenuItem *BahamasNassau1;
	TMenuItem *CanadaOttawa1;
	TMenuItem *CaymanIslandsGeorgeTown1;
	TMenuItem *CyprusNicosia1;
	TMenuItem *DenmarkCopenhagen1;
	TMenuItem *FranceParis1;
	TMenuItem *GermanyBerlin1;
	TMenuItem *ItalyRome1;
	TMenuItem *JapanTokyo1;
	TMenuItem *FijiSuva1;
	TMenuItem *SenegalDakar1;
	TMenuItem *SenegalDakar2;
	TMenuItem *CanadaVancouver1;
	TMenuItem *USA2;
	TMenuItem *PolandWarsaw1;
	TMenuItem *UkraineKyiv1;
	TMenuItem *UkraineKyiv2;
	TMenuItem *USAAnchorage1;
	TMenuItem *CookIslandsAvarua1;
	TPopupMenu *puLatitude;
	TMenuItem *MenuItem1;
	TMenuItem *MenuItem2;
	TMenuItem *urkiyeAnkara1;
	TMenuItem *SolomonIslands1;
	TMenuItem *CocosIslands1;
	TMenuItem *IcelandReykjavk1;
	TMenuItem *USAWalesAlaska1;
	TMenuItem *UnitedKingdomLondon1;
	TMenuItem *CanadaVancouver2;
	TMenuItem *CanadaVancouver3;
	TMenuItem *DenmarkCopenhagen2;
	TMenuItem *MoroccoTangier1;
	TMenuItem *MoroccoTangier2;
	TMenuItem *asmaniaHobart1;
	TMenuItem *asmaniaHobart2;
	TMenuItem *CameroonYaounde2;
	TMenuItem *MarshallIslandsMajuro1;
	TMenuItem *MarshallIslandsMajuro2;
	TMenuItem *FaroeIslandsTorshavn1;
	TMenuItem *BarbadosBridgetown1;
	TMenuItem *BarbadosBridgetown2;
	TMenuItem *Equator1;
	TMenuItem *HeardIslandandMcDonaldIslands1;
	TMenuItem *SvalbardandJanMayenLongyearbyen1;
	TMenuItem *SvalbardandJanMayenLongyearbyen2;
	TPopupMenu *puPercentage;
	TMenuItem *Excessrange1;
	TMenuItem *N21;
	TMenuItem *N51;
	TMenuItem *N101;
	TMenuItem *N151;
	TMenuItem *N201;
	TMenuItem *N251;
	TMenuItem *N252;
	TMenuItem *N501;
	TMenuItem *N502;
	TMenuItem *N751;
	TLabel *lExcessRange;
	TMenuItem *N1001;
	TMenuItem *N22;
	TMenuItem *miOpenRouteFolder;
	TGroupBox *gbGeneratedRoutes;
	TImage *Image1;
	TButton *bExportSelected;
	TButton *bExportSelectedText;
	TButton *bOpenStartMap;
	TButton *bOpenEndMap;
	TButton *bSaveRoutes;
	TStringGrid *sgRoutes;
	TButton *bExportSelectedXPlane;
	TCheckBox *cbAirportTypeAutomatic;
	TPageControl *pcGeography;
	TTabSheet *TabSheet7;
	TLabel *Label19;
	TLabel *Label35;
	TTabSheet *TabSheet3;
	TCheckBox *cbContinentAF;
	TCheckBox *cbContinentNA;
	TCheckBox *cbContinentAN;
	TCheckBox *cbContinentOC;
	TCheckBox *cbContinentAS;
	TCheckBox *cbContinentSA;
	TCheckBox *cbContinentEU;
	TTabSheet *TabSheet4;
	TComboBox *cbCountryList;
	TTabSheet *TabSheet5;
	TLabel *Label31;
	TBevel *Bevel3;
	TEdit *eRegionICO;
	TTabSheet *TabSheet6;
	TLabel *Label5;
	TLabel *Label7;
	TLabel *Label6;
	TLabel *labellongto;
	TEdit *eLatFrom;
	TEdit *eLatTo;
	TEdit *eLongTo;
	TEdit *eLongFrom;
	TMemo *mRouteDebug;
	TButton *bShowSearchParameters;
	void __fastcall FormCreate(TObject *Sender);
	void __fastcall FormClose(TObject *Sender, TCloseAction &Action);
	void __fastcall bUpdateAircraftClick(TObject *Sender);
	void __fastcall bUpdateAirportsClick(TObject *Sender);
	void __fastcall bGenerateClick(TObject *Sender);
	void __fastcall tbSaveClick(TObject *Sender);
	void __fastcall tbOpenClick(TObject *Sender);
	void __fastcall tbExportClick(TObject *Sender);
	void __fastcall tbExportItineraryClick(TObject *Sender);
	void __fastcall Createcustomaircrafttxt1Click(TObject *Sender);
	void __fastcall About1Click(TObject *Sender);
	void __fastcall sgRoutesClick(TObject *Sender);
	void __fastcall cbAircraftListChange(TObject *Sender);
	void __fastcall miSetGAClick(TObject *Sender);
	void __fastcall Airports1Click(TObject *Sender);
	void __fastcall bExportSelectedClick(TObject *Sender);
	void __fastcall bExportSelectedTextClick(TObject *Sender);
	void __fastcall Favourites1Click(TObject *Sender);
	void __fastcall bLockAircraftClick(TObject *Sender);
	void __fastcall bRandomAircraftClick(TObject *Sender);
	void __fastcall cbAircraftTypePropsClick(TObject *Sender);
	void __fastcall cbContinentAFClick(TObject *Sender);
	void __fastcall cbUseFlightTimeClick(TObject *Sender);
	void __fastcall cbUseDirectionClick(TObject *Sender);
	void __fastcall eLegsExit(TObject *Sender);
	void __fastcall eMinElevationExit(TObject *Sender);
	void __fastcall eAircraftRangeModifierExit(TObject *Sender);
	void __fastcall Label31Click(TObject *Sender);
	void __fastcall bOpenStartMapClick(TObject *Sender);
	void __fastcall bOpenEndMapClick(TObject *Sender);
	void __fastcall miShowTooltipsClick(TObject *Sender);
	void __fastcall cbTimeOfDayClick(TObject *Sender);
	void __fastcall tbCodeTestClick(TObject *Sender);
	void __fastcall eDirectionExit(TObject *Sender);
	void __fastcall Select1Click(TObject *Sender);
	void __fastcall eEndAirportICAOExit(TObject *Sender);
	void __fastcall miUseHomeAirportClick(TObject *Sender);
	void __fastcall SetasHomeairport1Click(TObject *Sender);
	void __fastcall puSelectICAOPopup(TObject *Sender);
	void __fastcall England1Click(TObject *Sender);
	void __fastcall N8Click(TObject *Sender);
	void __fastcall N9Click(TObject *Sender);
	void __fastcall DistancefromAtoB1Click(TObject *Sender);
	void __fastcall BarraAirport1Click(TObject *Sender);
	void __fastcall tbNewClick(TObject *Sender);
	void __fastcall miResetAircraftClick(TObject *Sender);
	void __fastcall miResetAirportsClick(TObject *Sender);
	void __fastcall miResetRouteClick(TObject *Sender);
	void __fastcall miRouteBrowserClick(TObject *Sender);
	void __fastcall cbRWAirlineClick(TObject *Sender);
	void __fastcall cbRWUseFlightTimeClick(TObject *Sender);
	void __fastcall pcRouteChange(TObject *Sender);
	void __fastcall eRWAirportExit(TObject *Sender);
	void __fastcall lStatsRoutesClick(TObject *Sender);
	void __fastcall lStatsAirportClick(TObject *Sender);
	void __fastcall lStatsAircraftClick(TObject *Sender);
	void __fastcall miRange1Click(TObject *Sender);
	void __fastcall AustraliaCanberra1Click(TObject *Sender);
	void __fastcall asmaniaHobart2Click(TObject *Sender);
	void __fastcall eMaxElevationExit(TObject *Sender);
	void __fastcall bSaveRoutesClick(TObject *Sender);
	void __fastcall miOpenRouteFolderClick(TObject *Sender);
	void __fastcall pcGeographyChange(TObject *Sender);
	void __fastcall FormKeyPress(TObject *Sender, System::WideChar &Key);
	void __fastcall bExportSelectedXPlaneClick(TObject *Sender);
	void __fastcall bShowSearchParametersClick(TObject *Sender);
	void __fastcall cbAirportTypeAutomaticClick(TObject *Sender);

private:	// User declarations

	bool AircraftDetailsHaveChanged = false;
	bool AirportDetailsHaveChanged = false;

	void BuildGUIFrom(AircraftLoadFilter&, AirportLoadFilter&, FlightFilter&);
	void InitialGUISetup();
	void ResetGUI();
	void SetLabelStatus(int, TLabel *label);
	void StatsGUI();
	void UpdateExcessRange();

	void RandomPreCheck();
	void RoutePreCheck();

	void GenerateRandomRoutes();
    void GenerateRealWorldRoutes();

	Aircraft GetAircraftFromSelection();

	bool UpdateRouteList();

	void UpdateAircraftList();

	AircraftLoadFilter BuildAircraftLoadFilterFromUI();
	AirportLoadFilter BuildAirportLoadFilterFromUI();
	FlightFilter BuildRouteLoadFilterFromUI();

	void UpdateCountryList();
    void UpdateRouteDescription(int);

	void SetAircraftSelections(bool, bool, bool, bool, bool, bool, bool, bool, bool, bool, bool);

public:		// User declarations
	__fastcall TfrmMain(TComponent* Owner);
};

extern PACKAGE TfrmMain *frmMain;

#endif
