//
// FlightSimAdventureCreator 1.0
//
// (c) Paul Alan Freshney 2022
//
// paul@freshney.org
// 
// https://github.com/MaximumOctopus/FlightSimAdventureCreator
// 
// 

#pragma once


#include <string>


namespace Location
{
	static const int ContinentCount = 7;

	static const std::wstring ContinentNames[ContinentCount] = { L"Africa", L"Antarctica", L"Asia", L"Europe", L"North America", L"Oceania", L"South America" };
	static const std::wstring ContinentShort[ContinentCount] = { L"AF", L"AN", L"AS", L"EU", L"NA", L"OC", L"SA" };

	static const int ISOCountriesCount = 249;

	static const std::wstring ISOCountries[ISOCountriesCount][2] =
	{ { L"AD", L"Andorra"},
	{ L"AE", L"United Arab Emirates" },
	{ L"AF", L"Afghanistan" },
	{ L"AG", L"Antigua and Barbuda" },
	{ L"AI", L"Anguilla" },
	{ L"AL", L"Albania" },
	{ L"AM", L"Armenia" },
	{ L"AO", L"Angola" },
	{ L"AQ", L"Antarctica" },
	{ L"AR", L"Argentina" },
	{ L"AS", L"American Samoa" },
	{ L"AT", L"Austria" },
	{ L"AU", L"Australia" },
	{ L"AW", L"Aruba" },
	{ L"AX", L"Åland Islands" },
	{ L"AZ", L"Azerbaijan" },
	{ L"BA", L"Bosnia and Herzegovina" },
	{ L"BB", L"Barbados" },
	{ L"BD", L"Bangladesh" },
	{ L"BE", L"Belgium" },
	{ L"BF", L"Burkina Faso" },
	{ L"BG", L"Bulgaria" },
	{ L"BH", L"Bahrain" },
	{ L"BI", L"Burundi" },
	{ L"BJ", L"Benin" },
	{ L"BL", L"Saint Barthélemy" },
	{ L"BM", L"Bermuda" },
	{ L"BN", L"Brunei Darussalam" },
	{ L"BO", L"Bolivia (Plurinational State of)" },
	{ L"BQ", L"Bonaire, Sint Eustatius and Saba" },
	{ L"BR", L"Brazil" },
	{ L"BS", L"Bahamas" },
	{ L"BT", L"Bhutan" },
	{ L"BV", L"Bouvet Island" },
	{ L"BW", L"Botswana" },
	{ L"BY", L"Belarus" },
	{ L"BZ", L"Belize" },
	{ L"CA", L"Canada" },
	{ L"CC", L"Cocos (Keeling) Islands" },
	{ L"CD", L"Congo, Democratic Republic of the" },
	{ L"CF", L"Central African Republic" },
	{ L"CG", L"Congo" },
	{ L"CH", L"Switzerland" },
	{ L"CI", L"Côte d'Ivoire" },
	{ L"CK", L"Cook Islands" },
	{ L"CL", L"Chile" },
	{ L"CM", L"Cameroon" },
	{ L"CN", L"China" },
	{ L"CO", L"Colombia" },
	{ L"CR", L"Costa Rica" },
	{ L"CU", L"Cuba" },
	{ L"CV", L"Cabo Verde" },
	{ L"CW", L"Curaçao" },
	{ L"CX", L"Christmas Island" },
	{ L"CY", L"Cyprus" },
	{ L"CZ", L"Czechia" },
	{ L"DE", L"Germany" },
	{ L"DJ", L"Djibouti" },
	{ L"DK", L"Denmark" },
	{ L"DM", L"Dominica" },
	{ L"DO", L"Dominican Republic" },
	{ L"DZ", L"Algeria" },
	{ L"EC", L"Ecuador" },
	{ L"EE", L"Estonia" },
	{ L"EG", L"Egypt" },
	{ L"EH", L"Western Sahara" },
	{ L"ER", L"Eritrea" },
	{ L"ES", L"Spain" },
	{ L"ET", L"Ethiopia" },
	{ L"FI", L"Finland" },
	{ L"FJ", L"Fiji" },
	{ L"FK", L"Falkland Islands" },
	{ L"FM", L"Micronesia (Federated States of)" },
	{ L"FO", L"Faroe Islands" },
	{ L"FR", L"France" },
	{ L"GA", L"Gabon" },
	{ L"GB", L"United Kingdom of Great Britain and Northern Ireland" },
	{ L"GD", L"Grenada" },
	{ L"GE", L"Georgia" },
	{ L"GF", L"French Guiana" },
	{ L"GG", L"Guernsey" },
	{ L"GH", L"Ghana" },
	{ L"GI", L"Gibraltar" },
	{ L"GL", L"Greenland" },
	{ L"GM", L"Gambia" },
	{ L"GN", L"Guinea" },
	{ L"GP", L"Guadeloupe" },
	{ L"GQ", L"Equatorial Guinea" },
	{ L"GR", L"Greece" },
	{ L"GS", L"South Georgia and the South Sandwich Islands" },
	{ L"GT", L"Guatemala" },
	{ L"GU", L"Guam" },
	{ L"GW", L"Guinea-Bissau" },
	{ L"GY", L"Guyana" },
	{ L"HK", L"Hong Kong" },
	{ L"HM", L"Heard Island and McDonald Islands" },
	{ L"HN", L"Honduras" },
	{ L"HR", L"Croatia" },
	{ L"HT", L"Haiti" },
	{ L"HU", L"Hungary" },
	{ L"ID", L"Indonesia" },
	{ L"IE", L"Ireland" },
	{ L"IL", L"Israel" },
	{ L"IM", L"Isle of Man" },
	{ L"IN", L"India" },
	{ L"IO", L"British Indian Ocean Territory" },
	{ L"IQ", L"Iraq" },
	{ L"IR", L"Iran (Islamic Republic of)" },
	{ L"IS", L"Iceland" },
	{ L"IT", L"Italy" },
	{ L"JE", L"Jersey" },
	{ L"JM", L"Jamaica" },
	{ L"JO", L"Jordan" },
	{ L"JP", L"Japan" },
	{ L"KE", L"Kenya" },
	{ L"KG", L"Kyrgyzstan" },
	{ L"KH", L"Cambodia" },
	{ L"KI", L"Kiribati" },
	{ L"KM", L"Comoros" },
	{ L"KN", L"Saint Kitts and Nevis" },
	{ L"KP", L"Korea (Democratic People's Republic of)" },
	{ L"KR", L"Korea, Republic of" },
	{ L"KW", L"Kuwait" },
	{ L"KY", L"Cayman Islands" },
	{ L"KZ", L"Kazakhstan" },
	{ L"LA", L"Lao People's Democratic Republic" },
	{ L"LB", L"Lebanon" },
	{ L"LC", L"Saint Lucia" },
	{ L"LI", L"Liechtenstein" },
	{ L"LK", L"Sri Lanka" },
	{ L"LR", L"Liberia" },
	{ L"LS", L"Lesotho" },
	{ L"LT", L"Lithuania" },
	{ L"LU", L"Luxembourg" },
	{ L"LV", L"Latvia" },
	{ L"LY", L"Libya" },
	{ L"MA", L"Morocco" },
	{ L"MC", L"Monaco" },
	{ L"MD", L"Moldova, Republic of" },
	{ L"ME", L"Montenegro" },
	{ L"MF", L"Saint Martin (French part)" },
	{ L"MG", L"Madagascar" },
	{ L"MH", L"Marshall Islands" },
	{ L"MK", L"North Macedonia" },
	{ L"ML", L"Mali" },
	{ L"MM", L"Myanmar" },
	{ L"MN", L"Mongolia" },
	{ L"MO", L"Macao" },
	{ L"MP", L"Northern Mariana Islands" },
	{ L"MQ", L"Martinique" },
	{ L"MR", L"Mauritania" },
	{ L"MS", L"Montserrat" },
	{ L"MT", L"Malta" },
	{ L"MU", L"Mauritius" },
	{ L"MV", L"Maldives" },
	{ L"MW", L"Malawi" },
	{ L"MX", L"Mexico" },
	{ L"MY", L"Malaysia" },
	{ L"MZ", L"Mozambique" },
	{ L"NA", L"Namibia" },
	{ L"NC", L"New Caledonia" },
	{ L"NE", L"Niger" },
	{ L"NF", L"Norfolk Island" },
	{ L"NG", L"Nigeria" },
	{ L"NI", L"Nicaragua" },
	{ L"NL", L"Netherlands" },
	{ L"NO", L"Norway" },
	{ L"NP", L"Nepal" },
	{ L"NR", L"Nauru" },
	{ L"NU", L"Niue" },
	{ L"NZ", L"New Zealand" },
	{ L"OM", L"Oman" },
	{ L"PA", L"Panama" },
	{ L"PE", L"Peru" },
	{ L"PF", L"French Polynesia" },
	{ L"PG", L"Papua New Guinea" },
	{ L"PH", L"Philippines" },
	{ L"PK", L"Pakistan" },
	{ L"PL", L"Poland" },
	{ L"PM", L"Saint Pierre and Miquelon" },
	{ L"PN", L"Pitcairn" },
	{ L"PR", L"Puerto Rico" },
	{ L"PS", L"Palestine, State of" },
	{ L"PT", L"Portugal" },
	{ L"PW", L"Palau" },
	{ L"PY", L"Paraguay" },
	{ L"QA", L"Qatar" },
	{ L"RE", L"Réunion" },
	{ L"RO", L"Romania" },
	{ L"RS", L"Serbia" },
	{ L"RU", L"Russian Federation" },
	{ L"RW", L"Rwanda" },
	{ L"SA", L"Saudi Arabia" },
	{ L"SB", L"Solomon Islands" },
	{ L"SC", L"Seychelles" },
	{ L"SD", L"Sudan" },
	{ L"SE", L"Sweden" },
	{ L"SG", L"Singapore" },
	{ L"SH", L"Saint Helena, Ascension and Tristan da Cunha" },
	{ L"SI", L"Slovenia" },
	{ L"SJ", L"Svalbard and Jan Mayen" },
	{ L"SK", L"Slovakia" },
	{ L"SL", L"Sierra Leone" },
	{ L"SM", L"San Marino" },
	{ L"SN", L"Senegal" },
	{ L"SO", L"Somalia" },
	{ L"SR", L"Suriname" },
	{ L"SS", L"South Sudan" },
	{ L"ST", L"Sao Tome and Principe" },
	{ L"SV", L"El Salvador" },
	{ L"SX", L"Sint Maarten (Dutch part)" },
	{ L"SY", L"Syrian Arab Republic" },
	{ L"SZ", L"Eswatini" },
	{ L"TC", L"Turks and Caicos Islands" },
	{ L"TD", L"Chad" },
	{ L"TF", L"French Southern Territories" },
	{ L"TG", L"Togo" },
	{ L"TH", L"Thailand" },
	{ L"TJ", L"Tajikistan" },
	{ L"TK", L"Tokelau" },
	{ L"TL", L"Timor-Leste" },
	{ L"TM", L"Turkmenistan" },
	{ L"TN", L"Tunisia" },
	{ L"TO", L"Tonga" },
	{ L"TR", L"Türkiye" },
	{ L"TT", L"Trinidad and Tobago" },
	{ L"TV", L"Tuvalu" },
	{ L"TW", L"Taiwan, Province of China" },
	{ L"TZ", L"Tanzania, United Republic of" },
	{ L"UA", L"Ukraine" },
	{ L"UG", L"Uganda" },
	{ L"UM", L"United States Minor Outlying Islands" },
	{ L"US", L"United States of America" },
	{ L"UY", L"Uruguay" },
	{ L"UZ", L"Uzbekistan" },
	{ L"VA", L"Holy See" },
	{ L"VC", L"Saint Vincent and the Grenadines" },
	{ L"VE", L"Venezuela (Bolivarian Republic of)" },
	{ L"VG", L"Virgin Islands (British)" },
	{ L"VI", L"Virgin Islands (U.S.)" },
	{ L"VN", L"Viet Nam" },
	{ L"VU", L"Vanuatu" },
	{ L"WF", L"Wallis and Futuna" },
	{ L"WS", L"Samoa" },
	{ L"YE", L"Yemen" },
	{ L"YT", L"Mayotte" },
	{ L"ZA", L"South Africa" },
	{ L"ZM", L"Zambia" },
	{ L"ZW", L"Zimbabwe" } };
}